### ISSUE TITLE
Consider support for outlines

### ISSUE THREAD

**Issue by eXpl0it3r** [skyrpex/RichText#17]
With one of the newer SFML 2.x version (iirc 2.4) the `sf::Text` class received outline support. Would be nice if RichText could make use of this. Additionally, `setColor` has been deprecated in favor of `setFillColor` in order to differentiate between fill and outline coloring.

Such a change would bumped the minimum required SFML version to something like 2.4.

**Comment by ventsin** [comment]
#24

**Comment by eXpl0it3r** [comment]
Fixed with #24
