### ISSUE TITLE
Access violation in RichText.hpp?

### ISSUE THREAD

**Issue by shingle-bells** [skyrpex/RichText#22]
Here's my error:
`Unhandled exception at 0x0FAA49EF (sfml-graphics-d-2.dll) in SFMLGameStates2.exe: 0xC0000005: Access violation reading location 0xCCCCCCD0. occurred`
It occurs in RichText.hpp in `RichText::Line::draw()`, so I don't know what I'm doing wrong.

**Comment by skyrpex** [comment]
I guess the problem was somewhere else? Regards.
